export const storeProducts = [
  {
    id: 1,
    title: "Strawberry juice",
    img: "https://i.ibb.co/dsZmMbB/stawberryjuice.png",
    price: 25900,
    company: "PT. Indofood",
    info: "Some of the most impressive health benefits of strawberry juice may include its ability to support skin health, strengthen the immune system, lower blood pressure, boost",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: "Pear Juice",
    img: "https://i.ibb.co/tsNsbJV/juic2-2-removebg-preview.png",
    price: 23000,
    company: "PT. Indofood",
    info: "Pears make for delicious juice. But pear juice might not be a good idea for everyone, especially for those who are sensitive to fructose.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: "Apple Juice",
    img: "https://i.ibb.co/vZSWPJj/applejuice.png",
    price: 27000,
    company: "PT. Indofood",
    info: "Apple juice is completely free of calories and fat and can lower cholesterol. A glass of apple juice is packed with various essential nutrients like vitamin A, vitamin C, Vitamin E, vitamin K and folate.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: "Kiwi Juice",
    img: "https://i.ibb.co/m8QCYQN/juic-2-removebg-preview.png",
    price: 29000,
    company: "PT. Indofood",
    info: "The skin of the kiwi contains many antioxidants. In fact, there is a higher concentration of antioxidants in the skin than in the flesh of the fruit ( 8 ",
    inCart: false,
    count: 0,
    total: 0,
  },
];

export const detailProduct = {
  id: 1,
  title: "Juice Mix",
  img: "hpstore-react/img/product-1.png",
  price: 10,
  company: "PT. Indofood",
  info: "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
  inCart: false,
  count: 0,
  total: 0,
};
